### ISSUE TITLE
Possible 1.12.2 version?

### ISSUE THREAD

**Issue by Mayravixx** [Emberwalker/Forgelin#10]
I need to ask, do you intend on updating forgelin to work with 1.12.2? I'm trying to use a mod on 1.12.2 that relies on LibrarianLib which also relies on forgelin, but the problem is, forgelin won't work on 1.12.2 because according to the curseforge page, the newest version is only for 1.8.9.

**Comment by Wyldern** [comment]
I don't write mods now, but Shadowfacts maintains an updated fork over at https://github.com/shadowfacts/Forgelin which should work for you!
