### ISSUE TITLE
1.7.10 Version

### ISSUE THREAD

**Issue by abvadabra** [Emberwalker/Forgelin#3]
I think it will be usefull to create a new branch for 1.7.10 version. I already implemented downgrade to 1.7.10 (https://github.com/FRedEnergy/Forgelin) but i don't want to create a pull request into master branch

**Comment by Wyldern** [comment]
The reason I'm only officially publishing a 1.8 version is due to the FML mechanics only being properly in 1.8 - for 1.7 my advice is to shade Kotlin manually.
