### ISSUE TITLE
Issue compiling, testing

### ISSUE THREAD

**Issue by The-Fireplace** [Emberwalker/Forgelin#4]
This is probably user(modder) error and not your mod, but when I googled the issue, all I found was that Kotlin needs an update, and Intellij wasn't showing any errors. Anyways, when I compile my mod, I get this:
http://paste.ubuntu.com/14862086/

Also, with the setup described in your readme, you can't test the mod in intellij either, you have to build and run the mod to test it

**Comment by Wyldern** [comment]
Hm yeah. I need to really do some updating/rewriting the documentation - the changes of late have caused a few issues.

**Comment by Wyldern** [comment]
Made a tracking bug for the re-architecting and re-documenting; #5

**Comment by Wyldern** [comment]
Alright, all the updates are done now - hopefully the new approach is simpler! Open a new issue if you have any issues with the new style. ^^

**Comment by LunNova** [comment]
Looks good :) Thanks

Are you sure about swapping to ISC license? https://www.gnu.org/licenses/license-list.html#ISC

> This license does have an unfortunate wording choice: it provides recipients with "Permission to use, copy, modify, and/or distribute this software…" This is roughly the same language from the license of Pine that the University of Washington later claimed prohibited people from distributing modified versions of the software.
> 
> ISC has told us they do not share the University of Washington's interpretation, and we have every reason to believe them. Thus, there's no reason to avoid software released under this license. However, to help make sure this language cannot cause any trouble in the future, we encourage developers to choose a different license for their own works. The Expat License and FreeBSD License are similarly permissive and brief.

**Comment by Wyldern** [comment]
I do like the BSD License, but I think ISC is flexible enough for my purposes. I don't plan to license-nitpick folk, so I'll leave it as a good faith thing.
