### ISSUE TITLE
Slim distribution to easily shadeable library form

### ISSUE THREAD

**Issue by Wyldern** [Emberwalker/Forgelin#5]
Basic plan is to strip the library down to just the adapter + utility classes, which can be safely included and shaded directly, leaving the shading of Kotlin itself to mods (the stdlib is pretty small anyways, even smaller if stripped to essentials.) This'll also need a large amount of documentation re-writing.

**Comment by LunNova** [comment]
What about getting the adapter included in Forge? Now that Kotlin is approaching a full release, it seems reasonably likely that a PR adding a Kotlin adapter would be merged.

**Comment by Wyldern** [comment]
I've talked to Lex and the gist I got was that Forge will not be accepting additional language support - they quite rightly want to 'farm out' adapters to others, since there's quite a burden on them to maintain it.
